url: https://mattshats.org
baseurl: /

# Site settings
title: Matt's Hats
email: contact@mattshats.org
description: ""


# Team names, titles and social links
people:
- name: Matt Williams
  #pic: 1
  position: Founder
- name: Jeanne Williams
  #pic: 1
  position: Lead
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #
- name: Josh Daugette
  position: Media


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MattsHatsCorp
  - title: facebook
    url: https://www.facebook.com/mattshatscorp/


# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty